gdg_todos/urls.py
"""GDG TODOs URL Configuration"""

from django.contrib import admin
from django.urls import path, include

from .views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('todos/', include(('todos.urls', 'todos'), namespace='todos')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
]

todos/urls.py
"""TODOs app URLs config"""

from django.urls import path

from . import views


urlpatterns = [
    path('', views.list, name='list'),
    path('create', views.create, name='create'),
    path('fulfill/<int:pk>', views.fulfill, name='fulfill'),
    path('delete/<int:pk>', views.delete, name='delete'),
]

users/urls.py
"""Users app URLs config"""

from django.urls import path

from . import views


urlpatterns = [
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
]

todos/models.py
"""TODOs app models"""

from django.contrib.auth.models import User
from django.db import models


class Todo(models.Model):
    """A simple TODO model"""
    task = models.CharField(max_length=255)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    done = models.BooleanField(blank=True, default=False)
    created_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.task} ({self.user.username})'

gdg_todos/views.py
"""GDG TODOs project views"""

from django.shortcuts import render


def index(request):
    """Shows main screen"""
    return render(request, 'index.html')

todos/views.py
"""TODOs app views"""

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404

from .models import Todo


@login_required
def list(request):
    """TODOs list"""
    finished_todos = Todo.objects.filter(user=request.user, done=True)
    not_finished_todos = Todo.objects.filter(user=request.user, done=False)
    context = {
        'finished_todos': finished_todos,
        'not_finished_todos': not_finished_todos
    }
    return render(request, 'todos/list.html', context)


@login_required
def create(request):
    """Creates a TODO"""
    if request.method == 'POST':
        task = request.POST.get('task')
        todo = Todo.objects.create(task=task, user=request.user)
        messages.success(
            request=request,
            message=f'"{todo.task}" se ha creado correctamente'
        )
        return redirect('todos:list')
    return render(request, 'todos/create.html')


@login_required
def fulfill(request, pk):
    """Fulfills a TODO"""
    todo = get_object_or_404(Todo, pk=pk)
    todo.done = True
    todo.save()
    messages.success(
        request=request,
        message=f'Has completado "{todo.task}"'
    )
    return redirect('todos:list')


@login_required
def delete(request, pk):
    """Deletes a TODO"""
    todo = get_object_or_404(Todo, pk=pk)
    todo.delete()
    messages.success(
        request=request,
        message=f'Se ha eliminado "{todo.task}"'
    )
    return redirect('todos:list')

users/views.py
"""Users app views"""

from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect


def login(request):
    """Authenticates a user"""
    context = {}
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = auth.authenticate(username=username, password=password)
        if user:
            auth.login(request, user)
            return redirect('todos:list')
        else:
            context['error'] = 'El usuario no pudo ser autenticado'

    return render(request, 'users/login.html', context)


def logout(request):
    """Logs out a user"""
    auth.logout(request)
    return redirect('index')

templates/_header.html
<header class="hero is-black is-bold">
  <div class="hero-body">
    {% load static %}
    <figure class="is-image">
      <img src="{% static 'img/logo.png' %}" alt="GDG UNAM LOGO" width="200" />
    </figure>
    <h1 class="title" style="margin-top: 15px">
      Lista de deberes
    </h1>
  </div>
</header>

templates/base.html
<!doctype html>
<html lang="es">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bulma@0.8.2/css/bulma.min.css"
    />
    <script
      defer
      src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"
    ></script>
    {% block css %}
    {% endblock css %}
    {% block title %}
    <title>GDG UNAM | TODOS</title>  
    {% endblock title %}
  </head>
  <body>
    {% block content %}
    {% endblock content %}
  </body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}
{% include '_header.html' %}
<section class="section">
  <h1 class="title">
    ¿Qué quieres hacer?
  </h1>
  <div class="buttons">
    
    {% if request.user.is_authenticated %}
    <a role="button" href="{% url 'todos:list' %}" class="button is-primary is-light">
      Ver TODOs
    </a>
    <a role="button" href="{% url 'todos:create' %}" class="button is-link is-light">
      Crear TODO
    </a>
    <a role="button" href="{% url 'users:logout' %}" class="button is-danger is-light">
      Cerrar Sesión
    </a>
    {% else %}
    <a role="button" href="{% url 'users:login' %}" class="button is-link is-light">
      Iniciar Sesión
    </a>
    {% endif %}
      
  </div>
  </ul>
</section>
{% endblock content %}
  

templates/todos/create.html
{% extends 'base.html' %}

{% block title %}
<title>Creat TODO</title>
{% endblock title %}

{% block content %}
{% include '_header.html' %}
<section class="section">
  <form action="{% url 'todos:create' %}" method="POST">
    {% csrf_token %}
    <h1 class="title">Crea un TODO</h1>
    <div class="field">
      <label class="label">Tarea:</label>
      <div class="control">
        <input class="input" name="task" type="text" required />
      </div>
    </div>
    <button type="submit" class="button is-success is-light">
      Crear
    </button>
    <a href="{% url 'todos:list' %}" class="button is-link is-light">
      Ver deberes
    </a>
  </form>
</section>
{% endblock content %}

templates/todos/list.html
{% extends 'base.html' %}

{% block title %}
<title>TODOs</title>
{% endblock title %}

{% block content %}
{% include '_header.html' %}
<section class="section">
  {% for message in messages %}
  <div class="notification is-success is-light">
    {{ message }}
  </div>
  {% endfor %}

  <h1 class="title">Lista de deberes</h1>
  <div class="buttons">
    <a href="{% url 'todos:create' %}" class="button is-primary is-light">
      Crear
    </a>
    <a href="{% url 'index' %}" class="button is-link is-light">
      Volver al inicio
    </a>
  </div>

  <p class="heading">Terminados</p>
  {% if finished_todos %}
  <div class="columns is-multiline">
    {% for todo in finished_todos %}
    <div class="column is-3">
      <div class="card">
        <header class="card-header">
          <p class="card-header-title">
            {{ todo.task }}
          </p>
          <span class="card-header-icon" aria-label="todo">
            <span class="icon">
              <i class="fas fa-thumbtack" aria-hidden="true"></i>
            </span>
          </span>
        </header>
        <footer class="card-footer">
          <a href="{% url 'todos:delete' todo.pk %}" class="card-footer-item">Eliminar</a>
        </footer>
      </div>
    </div>
    {% endfor %}
  </div>
  {% else %}
  <p>Aún no has terminado algún deber</p>
  {% endif %}
</section>

<section class="section">
  <p class="heading">Por hacer:</p>
  {% if not_finished_todos %}
  <div class="columns is-multiline">
    {% for todo in not_finished_todos %}
    <div class="column is-3">
      <div class="card">
        <header class="card-header">
          <p class="card-header-title">
            {{ todo.task }}
          </p>
          <span class="card-header-icon" aria-label="todo">
            <span class="icon">
              <i class="fas fa-thumbtack" aria-hidden="true"></i>
            </span>
          </span>
        </header>
        <footer class="card-footer">
          <a href="{% url 'todos:fulfill' todo.pk %}" class="card-footer-item">Cumplir</a>
        </footer>
      </div>
    </div>
    {% endfor %}
  </div>
  {% else %}
  <p>No tienes tareas pendientes</p>
  {% endif %}
</section>

{% endblock content %}

templates/users/login.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/login.css' %}" />
{% endblock css %}

{% block title %}
<title>Iniciar Sesión</title>
{% endblock title %}

{% block content %}
<section class="section">
  <form action="{% url 'users:login' %}" method="POST">
    {% csrf_token %}
    {% if error %}
    <div class="notification is-danger is-light">
      {{ error }}
    </div>
    {% endif %}

    <div class="box">
      <h1 class="title">Inicia sesión</h1>
      <div class="field">
        <label class="label">Nombre de usuario:</label>
        <div class="control">
          <input class="input" name="username" type="text" required />
        </div>
      </div>
      <div class="field">
        <label class="label">Contraseña:</label>
        <div class="control">
          <input class="input" name="password" type="password" required />
        </div>
      </div>
      <div class="buttons is-centered">
        <button type="submit" class="button is-primary is-light">
          Iniciar Sesión
        </button>
        <a
          role="button"
          href="{% url 'index' %}"
          class="button is-link is-light"
        >
          Regresar al inicio
        </a>
      </div>
    </div>
  </form>
</section>
{% endblock content %}